### ISSUE TITLE
react-microlink breaking with react-snap

### ISSUE THREAD

**Issue by dottjt** [microlinkhq/sdk#131]
## Questions & Answers

I'm just wondering, has anyone been able to get this to work with a react static site generation? I'm currently using react-snap and it breaks when generating the static assets, timing out on the particular page using microlinks. 

Any suggestions are greatly welcomed :)

**Comment by Kikobeats** [comment]
Hello, @dottjt!

About your question, yes, particularly the [microlink.io](https://microlink.io) (you can [take a look](https://github.com/microlinkhq/www) as well) is built using [GatsbyJS](https://gatsbyjs.org), so it could be a particular problem related with react-snap.

I closed the issue because is not directly with SDK, but feel free to follow the conversation :🙂
