### ISSUE TITLE
Is using raw `video` urls / mp4's legal in the preview?

### ISSUE THREAD

**Issue by luwes** [microlinkhq/sdk#272]
I was wondering about the legality of using raw video url's of a YouTube for example in you own player.
I love this example at https://microlink.io/sdk, the player UI looks really nice but to my knowledge this is not allowed by the terms of use by most video services. Did you have different findings or what are your thoughts on this?

**Comment by Kikobeats** [comment]
Hello, that's a fair question 🙂

Microlink is not re-hosting any kind of content, just detecting the public source URL.

It's the same way you can see a YouTube video because YouTube serves you that content.

The detection is done via [youtube-dl](https://youtube-dl.org), and this is particularly funny because [RIAA tried to takedown youtube-dl with no success](https://en.wikipedia.org/wiki/Youtube-dl#RIAA_takedown_request) (because is legal).

**Comment by luwes** [comment]
Thanks for the quick reply. Yes, that was pretty cool that youtube-dl was able to stay on Github. 
The use case is a bit different though. Anyway I'm just interested in what the limitations are using these assets as I'm building a somewhat similar API for video services https://github.com/playerxo/oembed
